on:
  push:
    branches:
      - main

name: 🚀 Deploy website to host on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install dotenv

      - name: Load environment variables from .env
        id: load-env
        run: |
          echo "Loading environment variables from .env"
          set -o allexport
          source .env
          set +o allexport
          echo "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY_BASE64" >> $GITHUB_ENV
          echo "PROD_FTP_PASSWORD=$PROD_FTP_PASSWORD" >> $GITHUB_ENV

      - name: Check loaded environment variables
        run: |
          echo "Loaded variables:"
          echo "SSH_PRIVATE_KEY_BASE64: $SSH_PRIVATE_KEY_BASE64"
          echo "PROD_FTP_PASSWORD: $PROD_FTP_PASSWORD"

      - name: Decode and set SSH Key
        id: decode-key
        run: |
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > private_ssh_key
          cat private_ssh_key  # Проверим содержимое ключа
          echo "SSH_PRIVATE_KEY=$(cat private_ssh_key)" >> $GITHUB_ENV
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ env.SSH_PRIVATE_KEY_BASE64 }}

      - name: 🔨 Build Project
        run: |
          npm cache clean --force
          npm install
          npm run build

      - name: 📂 Remove Files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 213.183.48.66
          username: root
          password: ${{ env.PROD_FTP_PASSWORD }}
          port: 22
          script: |
            if [ -d "/var/www/new.rechip-tuning.ru/htdocs/" ]; then
              find /var/www/new.rechip-tuning.ru/htdocs/ -mindepth 1 -delete
            else
              echo "Directory does not exist, nothing to remove"
            fi

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: "213.183.48.66"
          remote-user: "root"
          private-ssh-key: ${{ env.SSH_PRIVATE_KEY }}
          ssh-port: 22
          source-path: ./
          destination-path: /var/www/new.rechip-tuning.ru/htdocs/
