on:
  push:
    branches:
      - main

name: 🚀 Deploy website to host on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🔨 Build Project
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf package-lock.json
          npm install
          npm run build

      - name: 📂 Remove Files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          port: 22
          script: |
            if [ -d "/var/www/spb.rechip-tuning.ru/htdocs/" ]; then
              find /var/www/spb.rechip-tuning.ru/htdocs/ -mindepth 1 -delete
            else
              echo "Directory does not exist, nothing to remove"
            fi

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.PROD_FTP_HOST }}
          remote-user: ${{ secrets.PROD_FTP_USER }}
          private-ssh-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          ssh-port: 22
          source-path: ./
          destination-path: /var/www/spb.rechip-tuning.ru/htdocs/

      - name: ⭐ Start site via forever
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          port: 22
          script: |
            forever stopall || true
            forever start /var/www/spb.rechip-tuning.ru/htdocs/.output/server/index.mjs
